In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

In [3]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data'
columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
data = pd.read_csv(url, names=columns)
data

buying  maint  doors persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [4]:
data.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder

# LabelEncoder 객체 생성
label_encoder = LabelEncoder()

In [6]:
data['buying'].value_counts()

buying
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64

In [7]:
data['buying'] = label_encoder.fit_transform(data['buying'])
data['buying'].value_counts()

buying
3    432
0    432
2    432
1    432
Name: count, dtype: int64

In [8]:
data['maint'].value_counts()

maint
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64

In [9]:
data['maint'] = label_encoder.fit_transform(data['maint'])
data['maint'].value_counts()

maint
3    432
0    432
2    432
1    432
Name: count, dtype: int64

In [10]:
data['lug_boot'].value_counts()

lug_boot
small    576
med      576
big      576
Name: count, dtype: int64

In [11]:
data['lug_boot'] = label_encoder.fit_transform(data['lug_boot'])
data['lug_boot'].value_counts()

lug_boot
2    576
1    576
0    576
Name: count, dtype: int64

In [12]:
data['safety'].value_counts()

safety
low     576
med     576
high    576
Name: count, dtype: int64

In [13]:
data['safety'] = label_encoder.fit_transform(data['safety'])
data['safety'].value_counts()

safety
1    576
2    576
0    576
Name: count, dtype: int64

In [14]:
data['class'].value_counts()

class
unacc    1210
acc       384
good       69
vgood      65
Name: count, dtype: int64

In [15]:
data['class'] = label_encoder.fit_transform(data['class'])
data['class'].value_counts()

class
2    1210
0     384
1      69
3      65
Name: count, dtype: int64

In [16]:
data['doors'].value_counts()

doors
2        432
3        432
4        432
5more    432
Name: count, dtype: int64

In [17]:
data['doors'] = label_encoder.fit_transform(data['doors'])
data['doors'].value_counts()

doors
0    432
1    432
2    432
3    432
Name: count, dtype: int64

In [18]:
data

buying  maint  doors persons  lug_boot  safety  class
0          3      3      0       2         2       1      2
1          3      3      0       2         2       2      2
2          3      3      0       2         2       0      2
3          3      3      0       2         1       1      2
4          3      3      0       2         1       2      2
...      ...    ...    ...     ...       ...     ...    ...
1723       1      1      3    more         1       2      1
1724       1      1      3    more         1       0      3
1725       1      1      3    more         0       1      2
1726       1      1      3    more         0       2      1
1727       1      1      3    more         0       0      3

[1728 rows x 7 columns]

In [19]:
data['persons'].value_counts()

persons
2       576
4       576
more    576
Name: count, dtype: int64

In [20]:
data['persons'] = label_encoder.fit_transform(data['persons'])
data['persons'].value_counts()

persons
0    576
1    576
2    576
Name: count, dtype: int64

In [21]:
data

buying  maint  doors  persons  lug_boot  safety  class
0          3      3      0        0         2       1      2
1          3      3      0        0         2       2      2
2          3      3      0        0         2       0      2
3          3      3      0        0         1       1      2
4          3      3      0        0         1       2      2
...      ...    ...    ...      ...       ...     ...    ...
1723       1      1      3        2         1       2      1
1724       1      1      3        2         1       0      3
1725       1      1      3        2         0       1      2
1726       1      1      3        2         0       2      1
1727       1      1      3        2         0       0      3

[1728 rows x 7 columns]

In [22]:
X = data.drop('class', axis=1)
X

buying  maint  doors  persons  lug_boot  safety
0          3      3      0        0         2       1
1          3      3      0        0         2       2
2          3      3      0        0         2       0
3          3      3      0        0         1       1
4          3      3      0        0         1       2
...      ...    ...    ...      ...       ...     ...
1723       1      1      3        2         1       2
1724       1      1      3        2         1       0
1725       1      1      3        2         0       1
1726       1      1      3        2         0       2
1727       1      1      3        2         0       0

[1728 rows x 6 columns]

In [23]:
y = data['class']
y.value_counts()

class
2    1210
0     384
1      69
3      65
Name: count, dtype: int64

### 머신러닝 분류 RF, LR, DT

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,confusion_matrix

### RF

In [26]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))
print(classification_report(y_test,pred))


--- Radom Forest ---
0.9745370370370371
[[ 95   3   1   0]
 [  2  19   0   0]
 [  3   0 293   0]
 [  2   0   0  14]]
              precision    recall  f1-score   support

           0       0.93      0.96      0.95        99
           1       0.86      0.90      0.88        21
           2       1.00      0.99      0.99       296
           3       1.00      0.88      0.93        16

    accuracy                           0.97       432
   macro avg       0.95      0.93      0.94       432
weighted avg       0.98      0.97      0.97       432



### LR

In [27]:
# Build a logistic regression classifier and predict

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))
print(classification_report(y_test,pred_lr))


--- Logistic Regression Classifier ---
0.6550925925925926
[[ 11   0  84   4]
 [  1   0  20   0]
 [ 24   0 269   3]
 [  4   0   9   3]]
              precision    recall  f1-score   support

           0       0.28      0.11      0.16        99
           1       0.00      0.00      0.00        21
           2       0.70      0.91      0.79       296
           3       0.30      0.19      0.23        16

    accuracy                           0.66       432
   macro avg       0.32      0.30      0.30       432
weighted avg       0.56      0.66      0.59       432



### DT

In [28]:
# Build a decision tree classifier and predict

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))

print(classification_report(y_test,pred_dt))


--- Decision Tree Classifier ---
0.9768518518518519
[[ 92   4   3   0]
 [  0  21   0   0]
 [  2   0 294   0]
 [  1   0   0  15]]
              precision    recall  f1-score   support

           0       0.97      0.93      0.95        99
           1       0.84      1.00      0.91        21
           2       0.99      0.99      0.99       296
           3       1.00      0.94      0.97        16

    accuracy                           0.98       432
   macro avg       0.95      0.97      0.96       432
weighted avg       0.98      0.98      0.98       432

